version: '3.8'

services:
  simple-identity-server:
    build:
      context: .
      dockerfile: SimpleIdentityServer/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=IdentityServer;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - mcp-network
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: MCP.Server/Dockerfile
    ports:
      - "8081:80"
      - "8444:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=McpServer;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
      - Kafka__BootstrapServers=kafka:9092
      - IdentityServer__Authority=http://simple-identity-server
    depends_on:
      - db
      - kafka
      - simple-identity-server
    networks:
      - mcp-network
    restart: unless-stopped

  message-broker-kafka:
    build:
      context: .
      dockerfile: MessageBroker.Kafka/Dockerfile
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - kafka
    networks:
      - mcp-network
    restart: unless-stopped

  # Kafka and supporting services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mcp-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mcp-network

  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: YourStrong!Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mssql-data: