name: Build and Deploy Agency Appointments API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: agency-book-appointments    # Web app name
  DOTNET_VERSION: '9.0.x'                       # .NET version
  WORKING_DIRECTORY: '.'                        # Set your app's working directory
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write # For CodeQL analysis
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper versioning
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # Added CodeQL Analysis
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore "/p:NoWarn=CS0108,CS8618,CS8625,CS8603"
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" "/p:NoWarn=CS0108,CS8618,CS8625,CS8603"
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    # Added code coverage report
    - name: Generate code coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport
    
    # Perform CodeQL Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish "/p:NoWarn=CS0108,CS8618,CS8625,CS8603"
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: ${{ env.WORKING_DIRECTORY }}/publish
    
    # Added Docker build and push for SimpleIdentityServer
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract Docker metadata for SimpleIdentityServer
      id: meta-identity
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/identity-server
        tags: |
          type=sha,format=long
          latest
          
    - name: Build and push SimpleIdentityServer Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./SimpleIdentityServer/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-identity.outputs.tags }}
        labels: ${{ steps.meta-identity.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ADDITIONAL_BUILD_ARGS="/p:NoWarn=CS0108,CS8618,CS8625,CS8603"

    # Added Docker build and push for MCPServer
    - name: Extract Docker metadata for MCPServer
      id: meta-mcp
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/mcp-server
        tags: |
          type=sha,format=long
          latest
          
    - name: Build and push MCPServer Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./MCPServer/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-mcp.outputs.tags }}
        labels: ${{ steps.meta-mcp.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ADDITIONAL_BUILD_ARGS="/p:NoWarn=CS0108,CS8618,CS8625,CS8603"

    # Added Docker build and push for MessageBroker
    - name: Extract Docker metadata for MessageBroker
      id: meta-broker
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/message-broker
        tags: |
          type=sha,format=long
          latest
          
    - name: Build and push MessageBroker Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./MessageBroker/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-broker.outputs.tags }}
        labels: ${{ steps.meta-broker.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ADDITIONAL_BUILD_ARGS="/p:NoWarn=CS0108,CS8618,CS8625,CS8603"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-artifact
        path: ./publish
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
        
    # Added post-deployment health check
    - name: Check deployment health
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health)
        if [ "$response" = "200" ]; then
          echo "Deployment successful and application is healthy!"
        else
          echo "Health check failed with status: $response"
          exit 1
        fi
        
    # Added security scan
    - name: Run security scan for SimpleIdentityServer
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/identity-server:latest
        format: 'sarif'
        output: 'trivy-identity-results.sarif'
        
    - name: Upload security scan results for SimpleIdentityServer
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-identity-results.sarif'
