name: Build and Deploy Agency Appointments API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: agency-book-appointments    # Web app name
  DOTNET_VERSION: '9.0.x'                       # .NET version
  WORKING_DIRECTORY: '.'                        # Set your app's working directory

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: ${{ env.WORKING_DIRECTORY }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app-artifact
        path: ./publish
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish